### ISSUE TITLE
Prepending items / scrolling backwards

### ISSUE THREAD

**Issue by johtso** [johnsonjo4531/react-fast-masonry#1]
How does this behave if items are added to the beginning of the list?

Currently trying to find a way to achieve an infinite scrolling masonry layout that allows the user to click a button to "load previous", and then enable infinite scrolling behaviour in the upward direction.

Is this something I could possibly tweak this component to do, or is it at odds with how bricks.js is designed?

**Comment by johnsonjo4531** [comment]
@johtso, I just added [an example to the docs of your use case](https://johnsonjo4531.github.io/react-fast-masonry/?path=/story/fastmasonry--reverseloadmore). Is it kind of what you were thinking? 


Snippet below of render function from the above [example](https://johnsonjo4531.github.io/react-fast-masonry/?path=/story/fastmasonry--reverseloadmore):
```ts
export default function MyMasonry() {
  const [items, setItems] = React.useState([] as any[]);

  return (
    <div>
      <div
        style={{
          backgroundColor: "#ddd",
          padding: "0.7em",
          marginBottom: "1.4em"
        }}
        onClick={() => {
          setItems([...randomItems(), ...items]);
        }}
      >
        Load Previous
      </div>
      <MasonryLayout
        pack={true}
        sizes={[
          { columns: 1, gutter: 0, columnWidth: "100%" },
          { cq: 768, columns: 2, gutter: 20, columnWidth: 300 },
          { cq: 1024, columns: 3, gutter: 20, columnWidth: 400 }
        ]}
        items={items}
        renderItem={({ columnWidth }, index: number, key: any) => (
          <div
            style={{
              ...items[index],
              ...defaultStyles,
              width: columnWidth
            }}
            key={key}
          >
            {index}
          </div>
        )}
        loadMore={() => {
          setItems([...items, ...randomItems()]);
        }}
        awaitMore={true}
        pageSize={20}
        className="masonry"
      />
    </div>
  );
}

```

The way I did it above uses the pack prop... You could certainly optimize this a bit more by not always passing pack={true}, but I prefer to keep it somewhat simple in my examples like what I did above. The problem that you run into with adding things in reverse order and the reason you need to pack is that items are absolutely positioned with libraries like bricks.js, masonry, etc... the problem that is caused by adding items to the beginning of a list in bricks.js is that bricks tries to optimize items that have already been packed by not packing them again this is what it by default does and is called a update. I basically by default instead of packing items (which would update all items including ones already packed) when they are changed I update items (which only packs items that haven't already been packed.) If you add an item or items to the beginning you thus need a pack instead of an update, because usually adding some random set of items generally doesn't lined up with you already packed items below them and they somehow overlap.

If you wanted to optimize it a bit more I think you should just be able to send in pack true when you prepend and pack false after you append items.

More on the difference between pack and update at their respective links [for pack](https://github.com/callmecavs/bricks.js#pack) and [for update](https://github.com/callmecavs/bricks.js#update).

**Comment by johnsonjo4531** [comment]
By the way @johtso if you really want infinite scroll in the upward direction you may want something completely different then what I just showed you above, if that is the case let me know and I may be able to show you how it is done if you give me enough information about what you need.

**Comment by johtso** [comment]
Oh wow, thank you so much for the input!

Sorry if I wasn't super clear in my description of what I was trying to achieve.

So I currently have infinite scrolling using an onscroll listener. What I wanted was a button that would allow the user to start scrolling up the page in exactly the way they scroll down. 

Now that I've thought about it a bit more.. what I really want is to load a completely separate masonry element above the first, but have it pack _upwards_.

I'm guessing that's not something that bricks.js would be able to do though..

**Comment by johtso** [comment]
Excited to see you're playing around with making a reverse infinite scrolling example! Is that a 180 rotation I see? :)

The Storybook example currently freezes my browser btw. Maybe a bit too much infinity.

Another quick question. Is it possible to control how early the loadMore event is fired? For example if you wanted to make sure images have time to load by adding the next batch a good while before the user gets to the bottom of the currently loaded content.

**Comment by johnsonjo4531** [comment]
Something like [this example (see link)](https://johnsonjo4531.github.io/react-fast-masonry/?path=/story/fastmasonry--reverseinfinite) should kind of work. The only problem is that when reverse infinite scrolling it's

- It's not a very typical User Experience (UX). (Not the biggest possible issue just hopefully your users are aware they can scroll up infinitely.)
- A problem with infinite scroll in general is if you have information beyond the infinite scroll threshold it makes it impossible to access it (not a huge problem just make sure you don't make info on the page inaccessible).
- The browser generally works well with infinite scrolling going down, but not with scrolling up. I kind of had to hack a `scrollTarget?.scollIntoView` to shift the view downward after the view adds elements to the beginning. This shift must happen otherwise you would trigger the infinite scroll infinitely and it would just keep adding items to the beginning. You notice that's not something that's perfect, because you'll notice it doesn't completely scroll the element to where it was before. You can go ahead and try and get it to work better, but that's about the effort I'm willing to give to this problem for the moment.

 

```ts
export default function MyMasonry() {
  const container = useRef<HTMLDivElement | undefined>(undefined);
  const [items, setItems] = React.useState([] as any[]);
  const [scrollTarget, setScrollTarget] = React.useState<HTMLElement | null>(
    null
  );

  useLayoutEffect(() => {
    setTimeout(() => {
      scrollTarget?.scrollIntoView(true);
    }, 10);
  }, [items]);

  return (
    <div
      ref={r => {
        if (!r) return;
        container.current = r;
      }}
      style={{
        transform: `rotate(180deg)`
      }}
    >
      <MasonryLayout
        pack={true}
        sizes={[
          { columns: 1, gutter: 0, columnWidth: "100%" },
          { cq: 768, columns: 2, gutter: 20, columnWidth: 300 },
          { cq: 1024, columns: 3, gutter: 20, columnWidth: 400 }
        ]}
        items={items}
        renderItem={({ columnWidth }, index: number, key: any) => (
          <div
            style={{
              transform: `rotate(-180deg)`,
              ...items[index],
              ...defaultStyles,
              width: columnWidth
            }}
            key={key}
          >
            {index}
          </div>
        )}
        loadMore={() => {
          if (!container.current) return;
          setItems([...items, ...randomItems()]);
          const masonryEl = container.current.querySelector(".masonry");
          let scrollTarget2 = masonryEl?.lastChild;
          // Get the last HTMLElement (this will grab the sentinel)
          while (
            !(scrollTarget2 instanceof HTMLElement) ||
            scrollTarget2 === undefined
          ) {
            scrollTarget2 = scrollTarget2?.previousSibling;
          }
          // Get the last HTMLElement besides the sentinel.
          scrollTarget2 = scrollTarget2?.previousSibling;
          while (
            !(scrollTarget2 instanceof HTMLElement) || problem is that when reverse infinite scrolling it's

It's not a very typical User Experience (UX). (Not the biggest pos
            scrollTarget2 === undefined
          ) {
            scrollTarget2 = scrollTarget2?.previousSibling;
          }
          if (scrollTarget2) {
            setScrollTarget(scrollTarget2);
          }
        }}
        awaitMore={true}
        pageSize={20}
        className="masonry"
      />
    </div>
  );
}
```

**Comment by johnsonjo4531** [comment]
> Another quick question. Is it possible to control how early the loadMore event is fired? For example if you wanted to make sure images have time to load by adding the next batch a good while before the user gets to the bottom of the currently loaded content.

You should just be able to add a `threshold="500px"` or some other length to that effect to make it loadMore items sooner :D

**Comment by johnsonjo4531** [comment]
@johtso if I helped you sufficiently you can close this issue if you'd like, otherwise you can feel free to ask more :D

**Comment by johtso** [comment]
No that's awesome, thanks for the input!
